# Site settings
name: Jonathan Yagua
description: "Vicepresidente de Coderic"
url: "https://jonathan.coderic.net"


# Delete the lines you don't need
# about 5 elements are recomended
#github_username:  dashingcode
#codepen_username: your_codepen_username_goes_here
facebook_username: jonathan.yagua
#vk_username: your_vk_username_goes_here
twitter_username: elpanasamir
#google_plus_username: your_google_plus_username_goes_here
#linkedin_username: your_linked_in_username_goes_here
#vine_username:  your_vine_username_goes_here
instagram_username: jonathansamir1
#flickr_username: your_flickr_username_goes_here
#steam_username: your_steam_username_goes_here
#soundcloud_username:  your_soundcloud_username_goes_here
#stack_of_username: your_stack_overflow_account_id_number_goes_here
#reddit_username: your_reddit_username_goes_here
#medium_username:  your_medium_username_goes_here
#tumblr_username: your_tumblr_username_goes_here
#weibo_username: your_weibo_username_goes_here
#lastfm_username: your_lastfm_username_goes_here
blog_url: "https://www.youtube.com/channel/UC3B3aOIEb7RD2f3Ycvb_fDQ"
email: jonathan.yagua@coderic.net
public_key_url: "https://jonathanyagua.coderic.ner/id_rsa.pub"

avatar: yes
avatar_img_path: "imgs/jonathan-yagua.jpg"
# You can link to your GitHub image. That way it will get updated
# automatically whenever you change your GitHub profile picture
#avatar_img_path: "https://avatars2.githubusercontent.com/u/17301305"

front_img: no
front_img_path: "imgs/background.jpg"
#front_img_path: "https://external.url/image.jpg"


favicon_img: yes
favicon_img_path: "imgs/favicon.ico"
#favicon_img_path: "https://external.url/favicon.ico"


# Build settings
markdown: kramdown
permalink: pretty
