url: "https://coderic.org"
baseurl: "/JonathanYagua/"
title: "Coderic"
network: "TEAM"
name: "Jonathan Yagua"
description: "Vice President"
avatar_img_path: "imgs/jonathan-yagua.jpg"
permalink: pretty
remote_theme: Coderic/coderic.org
